name: "Hello Action 2"
description: "Greet someone"
inputs:
  name:
    description: "Who to greet"
    required: true
    default: "World"
  numOctocats:
    description: "Octocats count"
    required: true

outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps:
    - run: echo Hello ${{ inputs.name }} v1.0 !!
      shell: bash
    - run: echo num-octocats is ${{ inputs.numOctocats }} !
      shell: bash  
    - run: echo 'github.action_path is ${{ github.action_path }} !'
      shell: bash  
    - id: random-number-generator
      run: echo "::set-output name=random-id::$(echo $RANDOM)"
      shell: bash
