name: Download and Deploy Function App on Azure RBAC for .NET
description: Run "actions/download-artifact" and Deploy function app (Windows) with RBAC

inputs:
  azureLoginSecrets:
    description: Azure RBAC credentials
    required: true  
  azureFunctionAppName:
    description: Azure Function App name
    required: true
  slot-name: 
    description: "Azure Function app slot name"
    required: true
    default: "production"
    
runs:
  using: "composite"
  steps:
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ inputs.azureLoginSecrets }}
    - uses: actions/download-artifact@v2
      with:
        name: ${{ inputs.azureFunctionAppName }}
    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ inputs.azureFunctionAppName }}
        package: ${{ inputs.azureFunctionAppName }}
        slot-name: ${{ inputs.slot-name }}
