name: blob sandbox workflow

on:
  workflow_dispatch:

permissions:
      id-token: write
      contents: read
env:
  ACCOUNT_NAME: styokosandbox
  CONTAINER_NAME: test3
  BLOB_NAME: tsukihi.png

jobs:
  demo:
    runs-on: ubuntu-latest
    environment: prod
    steps:
    - uses: azure/login@v1
      with:
        client-id: ${{ vars.AZURE_CLIENT_ID }}
        tenant-id: ${{ vars.AZURE_TENANT_ID }}
        subscription-id: ${{ secret.AZURE_SUBSCRIPTION_ID }}
    - run: |
        end=`date -u -d "30 minutes" '+%Y-%m-%dT%H:%MZ'`
        az storage blob generate-sas --account-name $ACCOUNT_NAME -c ${{ env.CONTAINER_NAME }} -n $BLOB_NAME --permissions r --expiry $end --https-only
      
