name: blob sandbox workflow

on:
  workflow_dispatch:

permissions:
      id-token: write
      contents: read

jobs:
  demo:
    runs-on: ubuntu-latest
    environment: prod
    steps:
    - uses: azure/login@v1
      with:
        client-id: "bce0a6d6-b0ed-444e-9395-d11acae3a003"
        tenant-id: "1982bd18-2869-4bf4-aef9-ea424e027cba"
        subscription-id: "1b3190c4-138d-4ddf-8b9c-832ec58ddf2b"
      
