on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v2
      - id: hello
        uses: beachside-project/github-actions-sandbox/hello-action
        with:
          name: 'YOKOHAMA'
      - run: echo hello action random-number is ${{ steps.hello.outputs.random-number }}
        shell: bash
      - id: bye
        uses: beachside-project/github-actions-sandbox/goobye-action
        with:
          name: 'Atsushi'
      - run: echo goobye random-number ${{ steps.bye.outputs.random-number }}
        shell: bash
