name: Azure Functions for dotnet CI/CD via composite

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/funcion-app-dotnet-*.yml'
      
defaults:
  run:
    shell: bash
     
env:
  DOTNET_VERSION: '3.1.x'
  BUILD_CONFIGURATION: 'Release'
  FUNCTIONAPP_PACKAGE_PATH: 'function-app-sample/FunctionApp1'
  AZURE_FUNCTIONAPP_NAME: 'func-github-action-sandbox-dotnet'
  
jobs:
  build:
    name: Build and upload artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }} 
      # Creat build artifacts
      - name: Build and upload artifact
        uses: beachside-project/.github/workflows/composite/function-app-build-and-upload@main
        with:
          azureFunctionAppName: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          functionAppPackagePath: ${{ env.FUNCTIONAPP_PACKAGE_PATH }}

  # Deploy to staging
  deploy-function1:
    name: Deploy function-app-sample
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: beachside-project/.github/workflows/composite/function-app-download-and-deploy@main
        with:
          azureLoginSecrets: ${{ secrets.AZURE_RBAC_RG_FUNCTION_V3_DOTNET_CICD }}
          azureFunctionAppName: ${{ env.AZURE_FUNCTIONAPP_NAME }}
