name: Azure Functions for dotnet CI/CD .

on:
  workflow_dispatch:
  # push:
  #   branches: [ main ]
  #   paths:
  #     - '.github/workflows/funcion-app-dotnet-cicd.yml'
      
defaults:
  run:
    shell: bash
     
env:
  DOTNET_VERSION: '6.0.x'
  BUILD_CONFIGURATION: 'Release'
  FUNCTIONAPP_PACKAGE_PATH: 'function-app-sample/FunctionApp1'
  AZURE_FUNCTIONAPP_NAME: 'func-elle-sample1'
  
jobs:
  build:
    name: Build and upload artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }} 
      # Creat build artifacts
      - name: dotnet Publish
        run: |
          ls
          pushd './${{ env.FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet publish --configuration ${{ env.BUILD_CONFIGURATION }} --output ${{ github.workspace }}/outputs/${{ env.AZURE_FUNCTIONAPP_NAME }}
          popd
      #Publish build artifacts to GitHub
      - name: upload function app artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          path: ${{ github.workspace }}/outputs/${{ env.FUNCTIONAPP_NAME }}

  # Deploy to staging
  deploy-function1:
    name: Deploy function-app-sample
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/download-artifact@v3
        id: download
        with:
          name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          path: artifacts/${{ env.AZURE_FUNCTIONAPP_NAME }}
      - name: Echo download path for debug
        run: |
          echo download path is ${{steps.download.outputs.download-path}}
          ls
      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: artifacts/${{ env.AZURE_FUNCTIONAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE_FUNC_ELLE_SAMPLE1 }}
