name: Call internal composite actions 1
on: [push, pull_request]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v2
      - name: Extract branch name
        id: extract_branch      
        shell: bash
        run: |
          echo "::set-output name=CURRENT_BRANCH::${GITHUB_REF#refs/heads/}"
          echo "::set-output name=NAME::${GITHUB_REF#refs/*/}"
          echo "::set-output name=TAG::${GITHUB_REF#refs/tags/}"
      - run: |
          echo  "current branch is ${{ steps.extract_branch.outputs.CURRENT_BRANCH }}"
          echo  "NAME is ${{ steps.extract_branch.outputs.NAME }}"
          echo  "TAG is ${{ steps.extract_branch.outputs.TAG }}"          
      - id: hello
        uses: beachside-project/github-actions-sandbox/hello-action@main
        with:
          name: 'YOKOHAMA'
      - run: echo hello action random-number is ${{ steps.hello.outputs.random-number }}
        shell: bash
      - id: bye
        uses: beachside-project/github-actions-sandbox/goodbye-action@main
        with:
          name: 'Atsushi'
      - run: echo goobye random-number ${{ steps.bye.outputs.random-number }}
        shell: bash
