name: Call internal composite actions 1
on: [push, pull_request]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v2
      - id: hello
        uses: beachside-project/github-actions-sandbox/hello-action@main
        with:
          name: 'YOKOHAMA'
      - run: echo hello action random-number is ${{ steps.hello.outputs.random-number }}
        shell: bash
      - name: hello 2
        uses: ./.github/workflows/composite/hello-action2
        with:
          name: 'AY'
      - name: hello 2 @main
        uses: ./.github/workflows/composite/hello-action2@main
        with:
          name: 'AY'          
      - id: bye
        uses: beachside-project/github-actions-sandbox/goodbye-action@main
        with:
          name: 'Atsushi'
      - run: echo goobye random-number ${{ steps.bye.outputs.random-number }}
        shell: bash
