name: 'matrix and environment investigation'

on:
  push:
    branches: [main]
env:
  DOTNET_VERSION: '3.1.x'
  BUILD_CONFIGURATION: 'Release'
  AZURE_RESOURCE_GROUP: 'zenadvisor-prod-RG'
  # Geek
  GEEK_PROJECT_PATH: 'backend/src/Sflow.Geek.Web'
  GEEK_WEBAPP_NAME: 'zenadvisor-geek-backend'
  # Customer
  CUSTOMER_PROJECT_PATH: 'backend/src/Sflow.Customer.Web'
  CUSTOMER_WEBAPP_NAME: 'zenadvisor-customer-backend'
  
jobs:
  build_test:
    name: Build, Test and upload artifacts
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo 'Hello build_test job'
          echo 'Geek Web App name: ${{ env.GEEK_WEBAPP_NAME }}'
          
  deploy-matrix:
    name: Deploy
    needs: build_test
    runs-on: ubuntu-latest
    environment:
      name: staging
    strategy:
      matrix:
        webAppName:
          - ${{ env.GEEK_WEBAPP_NAME }}
          - ${{ env.CUSTOMER_WEBAPP_NAME }}
    steps:
      - name: echo-${{ matrix.webAppName }}
        run: echo ${{ matrix.webAppName }}  

    
  
