name: 'matrix and environment investigation'

on:
  push:
    branches: [main]
env:
  DOTNET_VERSION: '3.1.x'
  BUILD_CONFIGURATION: 'Release'
  AZURE_RESOURCE_GROUP: 'zenadvisor-prod-RG'
  # Geek
  GEEK_PROJECT_PATH: 'backend/src/Sflow.Geek.Web'
  GEEK_WEBAPP_NAME: 'zenadvisor-geek-backend'
  # Customer
  CUSTOMER_PROJECT_PATH: 'backend/src/Sflow.Customer.Web'
  CUSTOMER_WEBAPP_NAME: 'zenadvisor-customer-backend'
  
jobs:
  build_test:
    name: Build, Test and upload artifacts
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo 'Hello build_test job'
          echo 'Geek Web App name: ${{ env.GEEK_WEBAPP_NAME }}'
  

    
  
