name: Azure login using OIDC sample

on: [push]

permissions:
      id-token: write
      contents: read
      
jobs: 
  oidc-login:
    runs-on: ubuntu-latest

    steps:
        - name: OIDC Login to Azure
          uses: azure/login@v1
          with:
            client-id: ${{ secrets.AZURE_FIC_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_FIC_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_FIC_SUBSCRIPTION_ID }} 

        - name: run commands
          run: |
            az account show
            az group list
