name: Paths filter demo
on: 
  push:
    branches:
      - main
    paths:
      - 'paths-filter-demo/dir1/README.md'
  #   - 'paths-filter-demo/dir1/**'
  #    - '!README.md'
jobs:
  hello_job:
    runs-on: ubuntu-latest
    steps:
      - run: echo Hello
