name: PR trigger test

on:
  workflow_dispatch:
  pull_request:
    # types: [opened, synchronize]
    types:
      - assigned
      - unassigned
      - labeled
      - unlabeled
      - opened
      - edited
      - closed
      - reopened
      - synchronize
      - ready_for_review
      - locked
      - unlocked
      - review_requested
      - review_request_removed
      - labeled
      - unlabeled
    branches:
      - main
    paths:
      - "pr-trigger-target/*"

permissions:
  id-token: write
  contents: read
  
jobs:
  echo_job:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: echo
        run: |
          echo "workflow: ${{ github.workflow }}"
          echo "event_name: ${{ github.event_name }}"
          echo "ref_name: ${{ github.ref_name }}"
          echo "head_ref: ${{ github.head_ref }}"
          echo "base_ref: ${{ github.base_ref }}"