name: PR trigger test

on:
  workflow_dispatch:
  pull_request:
    # types: [opened, synchronize]
    types:
      - assigned
      - unassigned
      - labeled
      - unlabeled
      - opened
      - edited
      - closed
      - reopened
      - synchronize
      - ready_for_review
      - locked
      - unlocked
      - review_requested
      - review_request_removed
      - labeled
      - unlabeled
    branches:
      - main
    paths:
      - "pr-trigger-target/*"

permissions:
  id-token: write
  contents: read
  
jobs:
  echo_job:
    runs-on: windows-latest
    steps:
      - name: echo
        run: echo "Hello, world!"