name: sandbox workflow
on: 
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      deployment_env:
  
env:
  ENV_NAME: 'staging'


jobs:
  job1:
    runs-on: ubuntu-latest
    name: $ENV_NAME
    environment:
      name: ${{ inputs.deployment_target }}
    steps:
      - run: echo "hello $ENV_NAME"
