name: sandbox workflow
on: workflow_dispatch
env:
  ENV_NAME: 'staging'


jobs:
  job1:
    runs-on: ubuntu-latest
    name: $ENV_NAME
    environment:
      name: '${{ env.ENV_NAME }}'
    steps:
      - run: echo "hello $ENV_NAME"
