name: sandbox workflow
on: workflow_dispatch
env:
  ENV_NAME: 'staging'


jobs:
  job1:
    runs-on: ubuntu-latest
    name: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
    environment:
      name: staging
    steps:
      - run: echo "hello"
