name: sandbox workflow
on: 
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      deployment_env:
  
env:
  TARGET_ENV: 'staging'

jobs:
  job1:
    env:
      ENV_IN_JOB: 'staging2'
    runs-on: ubuntu-latest
    name: 'job1: ${{ inputs.deployment_env }}'
    environment:
      # name: ${{ inputs.deployment_env }}
      name: '$TARGET_ENV'
    steps:
      - run: echo "hello $TARGET_ENV"
      - name: 'via workflow_dispatch'
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: echo Hello workflow_dispatch
      - name: 'via notworkflow_dispatch'
        if: ${{ github.event_name != 'workflow_dispatch' }}
        run: echo Hello NOT workflow_dispatch
