name: sandbox workflow
on: workflow_dispatch
env:
  ENV_NAME: 'staging2'


jobs:
  job1:
    runs-on: ubuntu-latest
    name: env.ENV_NAME
    environment:
      name: $ENV_NAME
    steps:
      - run: echo "hello $ENV_NAME"
