name: Deploy ASP.NET Core app to Azure Web App

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/webapp-deploy-*.yml

env:
  AZURE_WEBAPP_NAME: 'app-webapp-sandbox-dotnet-beachside'
  AZURE_WEBAPP_PACKAGE_PATH: 'web-app-sample/WebApplication1'
  DOTNET_VERSION: '3.1.x'
  AZURE_WEBAPP_SLOT_NAME: 'Staging'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }} 
            # Run dotnet build and publish
      - name: dotnet build and publish
        run: |
          pushd ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          dotnet build --configuration Release --runtime win-x86
          dotnet publish -c Release --no-build --runtime win-x86 --self-contained false -o '${{ github.workspace }}/output/${{ env.AZURE_WEBAPP_NAME }}' 
          popd
      # Deploy to Azure Web apps
      - name: 'Run Azure webapp deploy action using publish profile credentials'
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE_APP_WEBAPP_SANDBOX_DOTNET_BEACHSIDE  }}
          package: '${{ github.workspace }}/output/${{ env.AZURE_WEBAPP_NAME }}'
          slot-name: ${{ env.AZURE_WEBAPP_SLOT_NAME }}
